import type { Metadata } from "next";
import "./globals.css";
import GeneralLayout from "./x-layouts/general.layout";
import { AuthProvider } from "./x-components/general.auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body suppressHydrationWarning className={`antialiased`}>
          <GeneralLayout>{children}</GeneralLayout>
        </body>
      </AuthProvider>
    </html>
  );
}
